.TH OLED LKCE 8 "Jul 2021" "Oracle Linux Enhanced Diagnostics" "0.5"

.SH NAME
oled lkce \- Linux Kernel Core Extractor

.SH SYNOPSIS
\fB oled lkce\fR [report \fIreport-options\fR] [configure \fIconfig-options\fR] [enable_kexec|disable_kexec|status] [clean|list|help]

.SH DESCRIPTION
\fBlkce command\fR is used to interact with Linux Kernel Core Extractor[LKCE]. It is used to generate report from vmcore. lkce can run user scripts in kexec kernel.

Once configured it can generate a report from a kexec kernel when system crashes. This is useful if the size of vmcore is too large to copy or send across for analysis or when generating vmcore is not preferred.

.SH OPTIONS
.TP
\fBreport <report-options>\fR
.RS 3
report-options:
.RE
.RS 3
\fB\-\-vmcore=\fI/path/to/vmcore\fR	- path to vmcore file for report generation (required)
.RE
.RS 3
[\fB\-\-vmlinux=\fI/path/to/vmlinux\fR]	- use this vmlinux instead of already configured value
.RE
.RS 3
[\fB\-\-crash_cmds=\fIcmd1,cmd2,...\fR]	- comma seperated crash cmds to be used in report generation instead of configured commands
.RE
.RS 3
[\fB\-\-outfile=\fI/path/to/outfile\fR]	- write output to outfile. By default output goes to stdout
.RE

.TP
\fBconfigure --default\fR - Configure with default values, overwriting the existing values.
.TP
\fBconfigure [--show]\fR  - Show the configured values. This is the default when no config-options are given.

.TP
\fBconfigure [config-options]\fR - other possible options
.RS 3
config-options:
.RE
.RS 3
[\fB\-\-vmlinux_path=\fI/path/to/vmlinux\fR]  - set vmliux_path to given value
.RE
.RS 3
[\fB\-\-crash_cmds_file=\fI/path/to/file\fR]  - set crash_cmds_file to given value
.RE
.RS 3
[\fB\-\-vmcore=\fIyes/no\fR]	- set vmcore to given value. Controls vmcore generation in kexec kernel.
.RE
.RS 3
[\fB\-\-max_out_files=\fI<number>\fR]	- set max_out_files to given value
.RE

.TP
\fBenable_kexec\fR - enable lkce to run user scripts in kexec kernel.

.TP
\fBdisable_kexec\fR - disable lkce to run user scripts in kexec kernel.

.TP
\fBstatus\fR - check the status of lkce configuration

.TP
\fBclean\fR - remove all but last 3 kexec report files.

.TP
\fBclean --all\fR - remove all the kexec report files.

.TP
\fBlist\fR - list the kexec report files.

.SH HOW TO SET UP LKCE TO GENERATE KDUMP REPORT
Make sure kexec-tools pkg is installed and you can generate a vmcore. Then, run these commands to enable lkce:
.RS 0
# yum install oled-tools
.RE
.RS 0
# oled lkce enable_kexec
.RE

Crash the system manually. Once the machine boots, run 'oled lkce list'. Verify the listed file for output. Keep the system in configured state to generate the report when it crashes.

.SH EXAMPLES
.RS 0
# oled lkce report --vmcore=/var/crash/127.0.0.1-2020-12-29-17\:17\:45/vmcore
.RE
.RS 0
# oled lkce report --vmcore=/var/crash/127.0.0.1-2020-12-29-17\:17\:45/vmcore --crash_cmds=bt,sys
.RE
.RS 0
# oled lkce report --vmcore=/var/crash/127.0.0.1-2020-12-29-17\:17\:45/vmcore --crash_cmds=bt,sys --outfile=/tmp/outfile.txt
.RE

.RS 0
# oled lkce configure --default
.RE
.RS 0
# oled lkce configure --show
.RE
.RS 0
# oled lkce configure --vmlinux_path=/usr/lib/debug/lib/modules/4.14.35-1902.3.1.el7uek.x86_64/vmlinux
.RE

# oled lkce help
.RE
.RS 0
# oled lkce enable_kexec
.RE
.RS 0
# oled lkce disable_kexec
.RE
.RS 0
# oled lkce status
.RE

.RS 0
# oled lkce clean
.RE
.RS 0
# oled lkce list
.RE

.SH MISC
.TP
kexec kernel is a secondary kernel used to collect the memory image[vmcore] of the first kernel when system crashes. kexec-tools pkg is used to configure the kexec kernel.

.TP
LKCE provides an environment inside kexec kernel to run user scripts. One such user script used by lkce to generate the vmcore report when the system crashes. LKCE links with kdump[of kexec-tools] service as kdump_pre hook to run scripts inside kexec kernel.

.SH FILES
.TP
/etc/oled/lkce/lkce.conf
